/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package card.game;

import java.awt.Color;

/**
 *
 * @author vajir
 */
public class Card extends javax.swing.JFrame {

    /**
     * Creates new form Card
     */
    static int millisecond =0;
    static int second =0;
    static int minuts =0;
    static int hour =0;
    
    static boolean state= true;
    public Card() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        start = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        Display = new javax.swing.JButton();
        t1 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        d2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 99));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(255, 102, 255));
        btn1.setFont(new java.awt.Font("Dungeon", 1, 18)); // NOI18N
        btn1.setForeground(new java.awt.Color(0, 0, 255));
        btn1.setText("1");
        btn1.setEnabled(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(255, 102, 255));
        btn2.setFont(new java.awt.Font("Dungeon", 1, 18)); // NOI18N
        btn2.setForeground(new java.awt.Color(0, 0, 255));
        btn2.setText("2");
        btn2.setEnabled(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(255, 102, 255));
        btn3.setFont(new java.awt.Font("Dungeon", 1, 18)); // NOI18N
        btn3.setForeground(new java.awt.Color(0, 0, 255));
        btn3.setText("3");
        btn3.setEnabled(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(255, 102, 255));
        btn4.setFont(new java.awt.Font("Dungeon", 1, 18)); // NOI18N
        btn4.setForeground(new java.awt.Color(0, 0, 255));
        btn4.setText("4");
        btn4.setEnabled(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(255, 102, 255));
        btn5.setFont(new java.awt.Font("Dungeon", 1, 18)); // NOI18N
        btn5.setForeground(new java.awt.Color(0, 0, 255));
        btn5.setText("5");
        btn5.setEnabled(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(255, 102, 255));
        btn6.setFont(new java.awt.Font("Dungeon", 1, 18)); // NOI18N
        btn6.setForeground(new java.awt.Color(0, 0, 255));
        btn6.setText("6");
        btn6.setEnabled(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(255, 102, 255));
        btn7.setFont(new java.awt.Font("Dungeon", 1, 18)); // NOI18N
        btn7.setForeground(new java.awt.Color(0, 0, 255));
        btn7.setText("7");
        btn7.setEnabled(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(255, 102, 255));
        btn8.setFont(new java.awt.Font("Dungeon", 1, 18)); // NOI18N
        btn8.setForeground(new java.awt.Color(0, 0, 255));
        btn8.setText("8");
        btn8.setEnabled(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(255, 102, 255));
        btn9.setFont(new java.awt.Font("Dungeon", 1, 18)); // NOI18N
        btn9.setForeground(new java.awt.Color(0, 0, 255));
        btn9.setText("9");
        btn9.setEnabled(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn10.setBackground(new java.awt.Color(255, 102, 255));
        btn10.setFont(new java.awt.Font("Dungeon", 1, 18)); // NOI18N
        btn10.setForeground(new java.awt.Color(0, 0, 255));
        btn10.setText("10");
        btn10.setEnabled(false);
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn11.setBackground(new java.awt.Color(255, 102, 255));
        btn11.setFont(new java.awt.Font("Dungeon", 1, 18)); // NOI18N
        btn11.setForeground(new java.awt.Color(0, 0, 255));
        btn11.setText("11");
        btn11.setEnabled(false);
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn12.setBackground(new java.awt.Color(255, 102, 255));
        btn12.setFont(new java.awt.Font("Dungeon", 1, 18)); // NOI18N
        btn12.setForeground(new java.awt.Color(0, 0, 255));
        btn12.setText("12");
        btn12.setEnabled(false);
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn13.setBackground(new java.awt.Color(255, 102, 255));
        btn13.setFont(new java.awt.Font("Dungeon", 1, 18)); // NOI18N
        btn13.setForeground(new java.awt.Color(0, 0, 255));
        btn13.setText("13");
        btn13.setEnabled(false);
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });

        btn14.setBackground(new java.awt.Color(255, 102, 255));
        btn14.setFont(new java.awt.Font("Dungeon", 1, 18)); // NOI18N
        btn14.setForeground(new java.awt.Color(0, 0, 255));
        btn14.setText("14");
        btn14.setEnabled(false);
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });

        btn15.setBackground(new java.awt.Color(255, 102, 255));
        btn15.setFont(new java.awt.Font("Dungeon", 1, 18)); // NOI18N
        btn15.setForeground(new java.awt.Color(0, 0, 255));
        btn15.setText("15");
        btn15.setEnabled(false);
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });

        btn16.setBackground(new java.awt.Color(255, 102, 255));
        btn16.setFont(new java.awt.Font("Dungeon", 1, 18)); // NOI18N
        btn16.setForeground(new java.awt.Color(0, 0, 255));
        btn16.setEnabled(false);
        btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn16ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("Complete");

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        start.setBackground(new java.awt.Color(255, 0, 51));
        start.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        start.setForeground(new java.awt.Color(0, 0, 204));
        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        stop.setBackground(new java.awt.Color(255, 0, 51));
        stop.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stop.setForeground(new java.awt.Color(0, 0, 204));
        stop.setText("Stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        Display.setBackground(new java.awt.Color(255, 255, 51));
        Display.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Display.setForeground(new java.awt.Color(51, 255, 255));
        Display.setEnabled(false);

        t1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t1.setText("00:");

        t2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t2.setText("00:");

        t3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t3.setText("00:");

        t4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t4.setText("00");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/card/game/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));

        d2.setBackground(new java.awt.Color(255, 255, 51));
        d2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        d2.setForeground(new java.awt.Color(51, 255, 255));
        d2.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jButton3.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn15, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(t1)
                                        .addGap(18, 18, 18)
                                        .addComponent(t2)
                                        .addGap(30, 30, 30)
                                        .addComponent(t3)
                                        .addGap(18, 18, 18)
                                        .addComponent(t4))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap()))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(764, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1)
                    .addComponent(t2)
                    .addComponent(t3)
                    .addComponent(t4))
                .addGap(92, 92, 92)
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn15, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn16, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(484, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int total = 1;
    
    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        
        displayState();        
        if(!(btn15.getText().equals(""))){
            if(btn16.getText().equals("")){
                btn16.setText(btn15.getText());
                btn15.setText("");
            }
            else if(btn11.getText().equals("")){
                btn11.setText(btn15.getText());
                btn15.setText("");
            }
            else if(btn14.getText().equals("")){
                btn14.setText(btn15.getText());
                btn15.setText("");
            }
        }
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        
        displayState();
        if(!(btn14.getText().equals(""))){
            if(btn15.getText().equals("")){
               btn15.setText(btn14.getText());
               btn14.setText("");
            }
                else if(btn10.getText().equals("")){
                btn10.setText(btn14.getText());
            btn14.setText("");
            }
            else if(btn13.getText().equals("")){
                btn13.setText(btn14.getText());
                btn14.setText("");
            }
        }
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        displayState();        
        if(!(btn13.getText().equals(""))){
            if(btn14.getText().equals("")){
               btn14.setText(btn13.getText());
               btn13.setText("");
            }
            else if(btn9.getText().equals("")){
               btn9.setText(btn13.getText());
               btn13.setText("");
            }
        }
        
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        displayState();        
        if (!(btn9.getText().equals(""))) {
            if(btn10.getText().equals("")){
                btn10.setText(btn9.getText());
                btn9.setText("");
            }
            else if(btn13.getText().equals("")){
                btn13.setText(btn9.getText());
                btn9.setText("");
            }
            else if(btn5.getText().equals("")){
                btn5.setText(btn9.getText());
               btn9.setText("");
            }
        }
        
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        displayState();        
        if (!(btn10.getText().equals(""))) {
            if(btn11.getText().equals("")){
               btn11.setText(btn10.getText());
               btn10.setText("");
            }
            else if(btn14.getText().equals("")){
               btn14.setText(btn10.getText());
               btn10.setText("");
            }
            else if(btn9.getText().equals("")){
               btn9.setText(btn10.getText());
               btn10.setText("");
            }
            else if(btn6.getText().equals("")){
               btn6.setText(btn10.getText());
               btn10.setText("");
            }
        }
        
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        displayState();        
        if (!(btn11.getText().equals(""))) {
            if(btn12.getText().equals("")){
                btn12.setText(btn11.getText());
                btn11.setText("");
            }
             else if(btn15.getText().equals("")){
                btn15.setText(btn11.getText());
                btn11.setText("");
            }
            else if(btn10.getText().equals("")){
                btn10.setText(btn11.getText());
                btn11.setText("");
            }
            else if(btn7.getText().equals("")){
                btn7.setText(btn11.getText());
                btn11.setText("");
            }  
        }
        
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        displayState();        
        if (!(btn12.getText().equals(""))) {
            if(btn16.getText().equals("")){
               btn16.setText(btn12.getText());
               btn12.setText("");
            }
            else if(btn11.getText().equals("")){
               btn11.setText(btn12.getText());
               btn12.setText("");
            }
            else if(btn8.getText().equals("")){
               btn8.setText(btn12.getText());
               btn12.setText("");
            }
        }
        
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        displayState();        
        if (!(btn5.getText().equals(""))) {
            if(btn1.getText().equals("")){
                btn1.setText(btn5.getText());
                btn5.setText("");
            }
            else if(btn6.getText().equals("")){
                btn6.setText(btn5.getText());
                btn5.setText("");
            }
            else if(btn9.getText().equals("")){
                btn9.setText(btn5.getText());
                btn5.setText("");
            }
        }
        
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        displayState();        
        if (!(btn6.getText().equals(""))) {
            if(btn2.getText().equals("")){
                btn2.setText(btn6.getText());
                btn6.setText("");
            }
            else if(btn7.getText().equals("")){
                btn7.setText(btn6.getText());
                btn6.setText("");
            }
            else if(btn10.getText().equals("")){
                btn10.setText(btn6.getText());
                btn6.setText("");
            }
            else if(btn5.getText().equals("")){
                btn5.setText(btn6.getText());
                btn6.setText("");
            }    
        }
        
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        displayState();        
        if (!(btn7.getText().equals(""))) {
            if(btn3.getText().equals("")){
                btn3.setText(btn7.getText());
                btn7.setText("");
            }
            else if(btn8.getText().equals("")){
                btn8.setText(btn7.getText());
                btn7.setText("");
            }
            else if(btn11.getText().equals("")){
                btn11.setText(btn7.getText());
                btn7.setText("");
            }
            else if(btn6.getText().equals("")){
                btn6.setText(btn7.getText());
                btn7.setText("");
            }   
        }
 
        
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        displayState();        
        if (!(btn8.getText().equals(""))) {
            if(btn4.getText().equals("")){
               btn4.setText(btn8.getText());
               btn8.setText("");
            }
            else if(btn7.getText().equals("")){
               btn7.setText(btn8.getText());
               btn8.setText("");
            }
            else if(btn12.getText().equals("")){
               btn12.setText(btn8.getText());
               btn8.setText("");
            }
        }
          
        
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        
        
        displayState();
        if (!(btn1.getText().equals(""))) {
            if(btn2.getText().equals("")){
               btn2.setText(btn1.getText());
               btn1.setText("");
        }
            else if(btn5.getText().equals("")){
               btn5.setText(btn1.getText());
               btn1.setText("");
            }
        }
           
        
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        displayState();
        if (!(btn2.getText().equals(""))) {
            if(btn3.getText().equals("")){
               btn3.setText(btn2.getText());
               btn2.setText("");
            }
            else if(btn6.getText().equals("")){
               btn6.setText(btn2.getText());
               btn2.setText("");
            }
            else if(btn1.getText().equals("")){
               btn1.setText(btn2.getText());
               btn2.setText("");
            }
        }
            
        
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        displayState();
        if (!(btn3.getText().equals(""))) {
            if(btn4.getText().equals("")){
               btn4.setText(btn3.getText());
               btn3.setText("");
            }
            else if(btn7.getText().equals("")){
               btn7.setText(btn3.getText());
               btn3.setText("");
            }
            else if(btn2.getText().equals("")){
               btn2.setText(btn3.getText());
               btn3.setText("");
            }
        }
          
        
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        displayState();
        
        if (!(btn4.getText().equals(""))) {
            if(btn8.getText().equals("")){
               btn8.setText(btn4.getText());
               btn4.setText("");
            }
            else if(btn3.getText().equals("")){
               btn3.setText(btn4.getText());
               btn4.setText("");
            }
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn16ActionPerformed
        displayState();
        if (!(btn16.getText().equals(""))) {
            if(btn15.getText().equals("")){
               btn15.setText(btn16.getText());
               btn16.setText("");
            }
            else if(btn12.getText().equals("")){
               btn12.setText(btn16.getText());
               btn16.setText("");
            }
        }
    }//GEN-LAST:event_btn16ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        refresh();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void refresh(){
        btn1.setText("9");
        btn2.setText("6");
        btn3.setText("2");
        btn4.setText("12");
        btn5.setText("3");
        btn6.setText("11");
        btn7.setText("14");
        btn8.setText("7");
        btn9.setText("15");
        btn10.setText("1");
        btn11.setText("");
        btn12.setText("10");
        btn13.setText("8");
        btn14.setText("5");
        btn15.setText("13");
        btn16.setText("4");
        
        state = false;
        
        hour = 0;
        minuts = 0;
        second = 0;
        millisecond = 0;
        
        t1.setText("00 : ");
        t2.setText("00 : ");
        t3.setText("00 : ");
        t4.setText("00");
    }
    
    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        
        refresh();
        
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        btn3.setEnabled(true);
        btn4.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);
        btn7.setEnabled(true);
        btn8.setEnabled(true);
        btn9.setEnabled(true);
        btn10.setEnabled(true);
        btn11.setEnabled(true);
        btn12.setEnabled(true);
        btn13.setEnabled(true);
        btn14.setEnabled(true);
        btn15.setEnabled(true);
        btn16.setEnabled(true);
        
        start.hide();
        stop.show();
        
        state = true;
        Thread t = new Thread(){
            public void run(){
                for(;;){
                if(state==true){
                    try{
                        sleep(1);
                        if (millisecond>1000) {
                            millisecond=0;
                            second++;
                        }
                        if (second>60) {
                            millisecond=0;
                            second=0;
                            minuts++;
                        }
                        if (minuts>60) {
                            millisecond=0;
                            second=0;
                            minuts=0;
                            hour ++;
                        }
                        
                        t4.setText(" : "+millisecond);
                        millisecond++;
                        t3.setText(" : "+second);
                        t2.setText(" : "+minuts);
                        t1.setText(""+hour);
                        
                    }
                    catch(Exception e){
                        
                    }
                }else{
                    break;
                }
            }
            }    
        };
        t.start();
    }//GEN-LAST:event_startActionPerformed
     
    //This method use for represent task ,when game windows open
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        this.setLocation(30, 20);
        System.out.println(btn1.getText());
        
        if(btn1.getText().equals("1")){
            btn1.setBackground(Color.red);
        }
        else if(!btn1.getText().equals("1")){
            btn1.setBackground(Color.pink);
        }
              
        else if(btn2.getText().equals("2")){
            btn2.setBackground(Color.red);
        }
        else if(!btn1.getText().equals("2")){
            btn2.setBackground(Color.pink);
        }
        
        else if(btn3.getText().equals("3")){
            btn3.setBackground(Color.red);
        }
        else if(!btn3.getText().equals("3")){
            btn3.setBackground(Color.pink);
        }
        
        else if(btn4.getText().equals("4")){
            btn4.setBackground(Color.red);
        }
        else if(!btn4.getText().equals("4")){
            btn4.setBackground(Color.pink);
        }
        
        else if(btn5.getText().equals("5")){
            btn5.setBackground(Color.red);
        }
        else if(!btn5.getText().equals("5")){
            btn5.setBackground(Color.pink);
        }
        
        else if(btn6.getText().equals("6")){
            btn6.setBackground(Color.red);
        }
        else if(!btn6.getText().equals("6")){
            btn6.setBackground(Color.pink);
        }
        
        
        else if(btn7.getText().equals("7")){
            btn7.setBackground(Color.red);
        }
        else if(!btn7.getText().equals("7")){
            btn7.setBackground(Color.pink);
        }
        
        else if(btn8.getText().equals("8")){
            btn8.setBackground(Color.red);
        }
        else if(!btn8.getText().equals("8")){
            btn8.setBackground(Color.pink);
        }
        
        else if(btn9.getText().equals("9")){
            btn9.setBackground(Color.red);
        }
        else if(!btn9.getText().equals("9")){
            btn9.setBackground(Color.pink);
        }
        
        else if(btn10.getText().equals("10")){
            btn10.setBackground(Color.red);
        }
        else if(!btn10.getText().equals("10")){
            btn5.setBackground(Color.pink);
        }
        
        else if(btn11.getText().equals("11")){
            btn11.setBackground(Color.red);
        }
        else if(!btn11.getText().equals("11")){
            btn11.setBackground(Color.pink);
        }
        
        
        
        else if(btn12.getText().equals("12")){
            btn12.setBackground(Color.red);
        }
        else if(!btn12.getText().equals("12")){
            btn12.setBackground(Color.pink);
        }
        
        else if(btn13.getText().equals("13")){
            btn13.setBackground(Color.red);
        }
        else if(!btn13.getText().equals("13")){
            btn13.setBackground(Color.pink);
        }
        
        else if(btn14.getText().equals("14")){
            btn14.setBackground(Color.red);
        }
        else if(!btn15.getText().equals("15")){
            btn15.setBackground(Color.pink);
        }
        
        stop.hide();
        start.show();
    }//GEN-LAST:event_formWindowOpened

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        stop.hide();
        start.show();
        
        btn1.setEnabled(false);
        btn2.setEnabled(false);
        btn3.setEnabled(false);
        btn4.setEnabled(false);
        btn5.setEnabled(false);
        btn6.setEnabled(false);
        btn7.setEnabled(false);
        btn8.setEnabled(false);
        btn9.setEnabled(false);
        btn10.setEnabled(false);
        btn11.setEnabled(false);
        btn12.setEnabled(false);
        btn13.setEnabled(false);
        btn14.setEnabled(false);
        btn15.setEnabled(false);
        btn16.setEnabled(false);
        
        
        state = false;
    }//GEN-LAST:event_stopActionPerformed

    public void displayState(){
        d2.setText(String.valueOf(total++));
    }
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        System.out.println(btn1.getText());
        
        if(btn1.getText().equals("1")){
            btn1.setBackground(Color.red);
        }
        else if(!btn1.getText().equals("1")){
            btn1.setBackground(Color.pink);
        }
              
        else if(btn2.getText().equals("2")){
            btn2.setBackground(Color.red);
        }
        else if(!btn1.getText().equals("2")){
            btn2.setBackground(Color.pink);
        }
        
        else if(btn3.getText().equals("3")){
            btn3.setBackground(Color.red);
        }
        else if(!btn3.getText().equals("3")){
            btn3.setBackground(Color.pink);
        }
        
        else if(btn4.getText().equals("4")){
            btn4.setBackground(Color.red);
        }
        else if(!btn4.getText().equals("4")){
            btn4.setBackground(Color.pink);
        }
        
        else if(btn5.getText().equals("5")){
            btn5.setBackground(Color.red);
        }
        else if(!btn5.getText().equals("5")){
            btn5.setBackground(Color.pink);
        }
        
        else if(btn6.getText().equals("6")){
            btn6.setBackground(Color.red);
        }
        else if(!btn6.getText().equals("6")){
            btn6.setBackground(Color.pink);
        }
        
        
        else if(btn7.getText().equals("7")){
            btn7.setBackground(Color.red);
        }
        else if(!btn7.getText().equals("7")){
            btn7.setBackground(Color.pink);
        }
        
        else if(btn8.getText().equals("8")){
            btn8.setBackground(Color.red);
        }
        else if(!btn8.getText().equals("8")){
            btn8.setBackground(Color.pink);
        }
        
        else if(btn9.getText().equals("9")){
            btn9.setBackground(Color.red);
        }
        else if(!btn9.getText().equals("9")){
            btn9.setBackground(Color.pink);
        }
        
        else if(btn10.getText().equals("10")){
            btn10.setBackground(Color.red);
        }
        else if(!btn10.getText().equals("10")){
            btn5.setBackground(Color.pink);
        }
        
        else if(btn11.getText().equals("11")){
            btn11.setBackground(Color.red);
        }
        else if(!btn11.getText().equals("11")){
            btn11.setBackground(Color.pink);
        }
        
        
        
        else if(btn12.getText().equals("12")){
            btn12.setBackground(Color.red);
        }
        else if(!btn12.getText().equals("12")){
            btn12.setBackground(Color.pink);
        }
        
        else if(btn13.getText().equals("13")){
            btn13.setBackground(Color.red);
        }
        else if(!btn13.getText().equals("13")){
            btn13.setBackground(Color.pink);
        }
        
        else if(btn14.getText().equals("14")){
            btn14.setBackground(Color.red);
        }
        else if(!btn15.getText().equals("15")){
            btn15.setBackground(Color.pink);
        }
        
        
        refresh();
        if(btn1.getText().equals("1") && btn2.getText().equals("2") && btn3.getText().equals("3") && btn4.getText().equals("4") && btn5.getText().equals("5") && btn6.getText().equals("6") && btn7.getText().equals("7") && btn8.getText().equals("8") && btn9.getText().equals("9") && btn10.getText().equals("10") && btn11.getText().equals("11") && btn12.getText().equals("12") && btn13.getText().equals("13") && btn14.getText().equals("14") && btn15.getText().equals("15") && btn16.getText().equals("")){
            Display.setText("You Win");
        }
        else{
            Display.setText("");
        }
    }//GEN-LAST:event_formWindowActivated

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Startup().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Card().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Display;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton d2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton start;
    private javax.swing.JButton stop;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    // End of variables declaration//GEN-END:variables
}
